### ISSUE TITLE
Goed bezig

### ISSUE THREAD

**Issue by xtrasmal** [ParadoxNL/Laravel-Mollie#1]
Bovenaan de zoekresultaten in Google! 
Nu nog wat code pushen en dan krijg je van mij een sterretje.

**Comment by ParadoxNL** [comment]
Het koste wat tijd, maar bij deze is het dan ook gebeurd :)

**Comment by xtrasmal** [comment]
Mooi weark! Nu kan ik eindelijk mijn computer weer uit het stof halen en bezig.
Ik zal mijn klant eens opbellen.
